# Generated by Django 5.1.15 on 2026-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(db_index=True, default="lobby", max_length=120),
                ),
                (
                    "player_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("body", models.TextField()),
                ("delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "livechat_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"],
                        name="livechat_me_channel_0c3898_idx",
                    )
                ],
            },
        ),
    ]
