# Generated by Django 5.1.15 on 2026-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "odds",
                    models.DecimalField(decimal_places=2, default=1.95, max_digits=6),
                ),
                ("featured", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sportsbook_event",
                "ordering": ["-featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("event", models.CharField(max_length=200)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                ("odds", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (stake not confirmed)"),
                            ("open", "Open"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sportsbook_bet",
                "ordering": ["-placed_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "placed_at"],
                        name="sportsbook__status_6fa77b_idx",
                    )
                ],
            },
        ),
    ]
