# Generated by Django 5.1.15 on 2026-06-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0002_event_previous_odds"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="odds_away",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="odds_draw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="sport",
            field=models.CharField(
                choices=[
                    ("football", "Football"),
                    ("basketball", "Basketball"),
                    ("tennis", "Tennis"),
                    ("mma", "MMA"),
                    ("boxing", "Boxing"),
                    ("baseball", "Baseball"),
                    ("athletics", "Athletics"),
                    ("esports", "Esports"),
                ],
                db_index=True,
                default="football",
                max_length=20,
            ),
        ),
    ]
