# Generated by Django 5.1.15 on 2026-06-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0003_event_odds_away_event_odds_draw_event_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="event_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bets",
                to="sportsbook.event",
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="selection",
            field=models.CharField(
                choices=[
                    ("home", "Home / 1"),
                    ("draw", "Draw / X"),
                    ("away", "Away / 2"),
                ],
                default="home",
                max_length=10,
            ),
        ),
    ]
