# Generated by Django 5.1.15 on 2026-06-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0004_bet_event_ref_bet_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                ("combined_odds", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (stake not confirmed)"),
                            ("open", "Open"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sportsbook_betslip",
                "ordering": ["-placed_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "placed_at"],
                        name="sportsbook__status_994f68_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BetLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                (
                    "selection",
                    models.CharField(
                        choices=[
                            ("home", "Home / 1"),
                            ("draw", "Draw / X"),
                            ("away", "Away / 2"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                ("odds", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "event_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legs",
                        to="sportsbook.event",
                    ),
                ),
                (
                    "slip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="sportsbook.betslip",
                    ),
                ),
            ],
            options={
                "db_table": "sportsbook_betleg",
                "ordering": ["id"],
            },
        ),
    ]
