# Generated by Django 5.1.15 on 2026-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0005_betslip_betleg"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
