# Generated by Django 5.1.15 on 2026-06-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0006_event_external_id_event_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("provider", models.CharField(blank=True, default="", max_length=20)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sportsbook_team",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="unique_team_provider_external_id",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_events",
                to="sportsbook.team",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_events",
                to="sportsbook.team",
            ),
        ),
    ]
