# Generated by Django 5.1.15 on 2026-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0007_team_event_away_team_event_home_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20, unique=True)),
                ("api_key", models.CharField(blank=True, default="", max_length=200)),
                ("base_url", models.URLField(blank=True, default="")),
            ],
            options={
                "db_table": "sportsbook_provider_credential",
            },
        ),
    ]
