# Generated by Django 5.1.15 on 2026-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0008_providercredential"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("provider", "external_id"),
                name="unique_provider_external_id",
            ),
        ),
    ]
