# Generated by Django 5.1.15 on 2026-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0009_event_unique_provider_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="api-football", max_length=20)),
                ("league_id", models.PositiveIntegerField()),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sportsbook_league_setting",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "league_id"), name="unique_league_setting"
                    )
                ],
            },
        ),
    ]
