# Generated by Django 5.1.15 on 2026-09-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0010_leaguesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="elapsed",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ht_score_away",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ht_score_home",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="score_away",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="score_home",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("goals", "Goals"),
                            ("halves", "Halves"),
                            ("handicap", "Handicaps"),
                            ("score", "Correct score"),
                            ("teams", "Team"),
                            ("specials", "Specials"),
                        ],
                        default="main",
                        max_length=12,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("match_result", "1X2"),
                            ("double_chance", "Double chance"),
                            ("draw_no_bet", "Draw no bet"),
                            ("over_under", "Total goals over/under"),
                            ("home_over_under", "Home team goals over/under"),
                            ("away_over_under", "Away team goals over/under"),
                            ("btts", "Both teams to score"),
                            ("asian_handicap", "Asian handicap"),
                            ("handicap_result", "Handicap result (3-way)"),
                            ("correct_score", "Correct score"),
                            ("exact_goals", "Exact total goals"),
                            ("odd_even", "Odd/even goals"),
                            ("ht_ft", "Half time/full time"),
                            ("highest_scoring_half", "Highest scoring half"),
                            ("clean_sheet_home", "Clean sheet (home)"),
                            ("clean_sheet_away", "Clean sheet (away)"),
                            ("win_to_nil_home", "Win to nil (home)"),
                            ("win_to_nil_away", "Win to nil (away)"),
                            ("manual", "Manually settled"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("ft", "Full time"),
                            ("1h", "1st half"),
                            ("2h", "2nd half"),
                        ],
                        default="ft",
                        max_length=2,
                    ),
                ),
                (
                    "line",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_open", models.BooleanField(default=True)),
                ("settled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markets",
                        to="sportsbook.event",
                    ),
                ),
            ],
            options={
                "db_table": "sportsbook_market",
                "ordering": ["sort_order", "line", "id"],
            },
        ),
        migrations.CreateModel(
            name="MarketOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=24)),
                ("label", models.CharField(max_length=60)),
                ("odds", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "previous_odds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="sportsbook.market",
                    ),
                ),
            ],
            options={
                "db_table": "sportsbook_market_outcome",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="bet",
            name="outcome_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bets",
                to="sportsbook.marketoutcome",
            ),
        ),
        migrations.AddField(
            model_name="betleg",
            name="outcome_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legs",
                to="sportsbook.marketoutcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("event", "key"), name="unique_market_key_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketoutcome",
            constraint=models.UniqueConstraint(
                fields=("market", "key"), name="unique_outcome_key_per_market"
            ),
        ),
    ]
