# Generated by Django 5.1.15 on 2026-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0011_markets"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="match_facts",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="metric",
            field=models.CharField(
                choices=[
                    ("goals", "Goals"),
                    ("corners", "Corners"),
                    ("cards", "Cards"),
                ],
                default="goals",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="market",
            name="group",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("goals", "Goals"),
                    ("halves", "Halves"),
                    ("handicap", "Handicaps"),
                    ("score", "Correct score"),
                    ("teams", "Team"),
                    ("corners", "Corners"),
                    ("cards", "Cards"),
                    ("scorers", "Goalscorers"),
                    ("specials", "Specials"),
                ],
                default="main",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="kind",
            field=models.CharField(
                choices=[
                    ("match_result", "1X2"),
                    ("double_chance", "Double chance"),
                    ("draw_no_bet", "Draw no bet"),
                    ("over_under", "Total goals over/under"),
                    ("home_over_under", "Home team goals over/under"),
                    ("away_over_under", "Away team goals over/under"),
                    ("btts", "Both teams to score"),
                    ("asian_handicap", "Asian handicap"),
                    ("handicap_result", "Handicap result (3-way)"),
                    ("correct_score", "Correct score"),
                    ("exact_goals", "Exact total goals"),
                    ("odd_even", "Odd/even goals"),
                    ("ht_ft", "Half time/full time"),
                    ("highest_scoring_half", "Highest scoring half"),
                    ("clean_sheet_home", "Clean sheet (home)"),
                    ("clean_sheet_away", "Clean sheet (away)"),
                    ("win_to_nil_home", "Win to nil (home)"),
                    ("win_to_nil_away", "Win to nil (away)"),
                    ("win_to_nil", "Win to nil (either team)"),
                    ("team_to_score_home", "Home team to score"),
                    ("team_to_score_away", "Away team to score"),
                    ("home_exact_goals", "Home team exact goals"),
                    ("away_exact_goals", "Away team exact goals"),
                    ("result_btts", "Result & both teams to score"),
                    ("result_total", "Result & total goals"),
                    ("win_both_halves", "Win both halves"),
                    ("win_either_half", "Win either half"),
                    ("score_both_halves", "Team to score in both halves"),
                    ("first_team_to_score", "Team to score first"),
                    ("last_team_to_score", "Team to score last"),
                    ("own_goal", "Own goal in match"),
                    ("red_card", "Red card in match"),
                    ("anytime_scorer", "Anytime goalscorer"),
                    ("first_scorer", "First goalscorer"),
                    ("last_scorer", "Last goalscorer"),
                    ("manual", "Manually settled"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="marketoutcome",
            name="key",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="marketoutcome",
            name="label",
            field=models.CharField(max_length=80),
        ),
    ]
