# Generated by Django 5.1.15 on 2026-09-28 18:15

from decimal import Decimal

from django.db import migrations, models


def flag_unpriced_feed_events(apps, schema_editor):
    """Feed-imported events that never received odds still carry the 1.95
    placeholder with no draw/away price — mark them unpriced."""
    Event = apps.get_model('sportsbook', 'Event')
    Event.objects.filter(
        provider='api-football', odds=Decimal('1.95'), odds_draw__isnull=True,
        odds_away__isnull=True, previous_odds__isnull=True,
    ).update(has_odds=False)


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0012_auto_settlement_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="has_odds",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(flag_unpriced_feed_events, migrations.RunPython.noop),
    ]
