# Generated by Django 5.1.15 on 2026-10-01 16:16

import django.db.models.deletion
from django.db import migrations, models


# Ids from apps.sportsbook.models.league.FEATURED_LEAGUES at the time of writing
# (migrations must not import live model code).
FEATURED = (2, 39, 140, 135, 78, 61, 3, 848, 1, 4, 94, 88, 203, 253, 71, 288)


def order_existing_leagues(apps, schema_editor):
    LeagueSetting = apps.get_model('sportsbook', 'LeagueSetting')
    for position, league_id in enumerate(FEATURED, start=1):
        LeagueSetting.objects.filter(league_id=league_id).update(sort_order=position * 10)


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0014_in_play"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaguesetting",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="event",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="sportsbook.leaguesetting",
            ),
        ),
        migrations.AddField(
            model_name="leaguesetting",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="leaguesetting",
            name="flag_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="leaguesetting",
            name="logo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="leaguesetting",
            name="sort_order",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.RunPython(order_existing_leagues, migrations.RunPython.noop),
    ]
