# Generated by Django 5.1.15 on 2026-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0016_remove_demo_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("selections", models.JSONField(default=list)),
                (
                    "player_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("loads", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sportsbook_bookingcode",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MultiBetBonusTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_legs", models.PositiveSmallIntegerField(unique=True)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sportsbook_multibetbonustier",
                "ordering": ["min_legs"],
            },
        ),
        migrations.AddField(
            model_name="betslip",
            name="bonus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="betslip",
            name="bonus_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
