# Generated by Django 5.1.15 on 2026-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0018_default_multibet_bonus_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="prices_locked",
            field=models.BooleanField(default=False),
        ),
    ]
