# Generated by Django 5.1.15 on 2026-10-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsbook", "0019_event_prices_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("allow_partial", models.BooleanField(default=True)),
                (
                    "in_play",
                    models.BooleanField(
                        default=True,
                        help_text="Offer cash-out while matches are being played.",
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sportsbook_cashout_settings",
            },
        ),
        migrations.AddField(
            model_name="bet",
            name="cashed_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="cashout_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bet",
            name="stake_cashed_out",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="betslip",
            name="cashed_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="betslip",
            name="cashout_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="betslip",
            name="stake_cashed_out",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="bet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (stake not confirmed)"),
                    ("accepting", "Accepting (in-play delay)"),
                    ("open", "Open"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("void", "Void"),
                    ("rejected", "Rejected (in-play)"),
                    ("cashed_out", "Cashed out"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="betslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (stake not confirmed)"),
                    ("accepting", "Accepting (in-play delay)"),
                    ("open", "Open"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("void", "Void"),
                    ("rejected", "Rejected (in-play)"),
                    ("cashed_out", "Cashed out"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Cashout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("stake_portion", models.DecimalField(decimal_places=2, max_digits=12)),
                ("full", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashouts",
                        to="sportsbook.bet",
                    ),
                ),
                (
                    "slip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashouts",
                        to="sportsbook.betslip",
                    ),
                ),
            ],
            options={
                "db_table": "sportsbook_cashout",
                "ordering": ["-created_at"],
            },
        ),
    ]
