# Generated by Django 5.1.15 on 2026-10-09 16:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JetRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("betting", "Taking bets"),
                            ("flying", "Flying"),
                            ("crashed", "Crashed"),
                        ],
                        db_index=True,
                        default="betting",
                        max_length=8,
                    ),
                ),
                ("server_seed", models.CharField(max_length=64)),
                ("seed_hash", models.CharField(max_length=64)),
                ("crash_point", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "house_edge_percent",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("betting_ends_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("crashed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_stake",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("bet_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "jet_round",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="JetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "house_edge_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=4
                    ),
                ),
                (
                    "min_bet",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.10"), max_digits=10
                    ),
                ),
                (
                    "max_bet",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                (
                    "max_win",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=12
                    ),
                ),
                (
                    "max_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000.00"), max_digits=10
                    ),
                ),
                (
                    "round_stake_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=12
                    ),
                ),
                ("betting_seconds", models.PositiveSmallIntegerField(default=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name_plural": "Jet settings",
                "db_table": "jet_settings",
            },
        ),
        migrations.CreateModel(
            name="JetBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("display_name", models.CharField(max_length=20)),
                ("slot", models.PositiveSmallIntegerField(default=1)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "auto_cashout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Riding"),
                            ("cashed", "Cashed out"),
                            ("lost", "Lost"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "cashout_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="jet.jetround",
                    ),
                ),
            ],
            options={
                "db_table": "jet_bet",
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "player_id", "slot"),
                        name="jet_one_bet_per_slot",
                    )
                ],
            },
        ),
    ]
