# Generated by Django 5.1.15 on 2026-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jetsettings",
            name="display_name",
            field=models.CharField(default="BetBlits Aviator", max_length=40),
        ),
    ]
