# Generated by Django 5.1.15 on 2026-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jet", "0002_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jetsettings",
            name="bot_count",
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="bots_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
