# Generated by Django 5.1.15 on 2026-10-10 12:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jet", "0003_bots"),
    ]

    operations = [
        migrations.CreateModel(
            name="JetChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chat", "Player message"),
                            ("win", "Big win"),
                            ("rain", "Rain"),
                            ("system", "Notice"),
                        ],
                        default="chat",
                        max_length=8,
                    ),
                ),
                (
                    "player_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=20)),
                ("body", models.CharField(max_length=200)),
                ("hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "jet_chat_message",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="JetChatMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(unique=True)),
                ("until", models.DateTimeField()),
                ("by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "jet_chat_mute",
            },
        ),
        migrations.AddField(
            model_name="jetbet",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="chat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="last_rain_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="rain_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="rain_daily_budget",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="rain_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="rain_every_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="rain_players",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="JetFreeBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(default="rain", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_bet",
                        to="jet.jetbet",
                    ),
                ),
            ],
            options={
                "db_table": "jet_free_bet",
                "ordering": ["expires_at", "id"],
            },
        ),
    ]
