# Generated by Django 5.1.15 on 2026-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jet", "0004_chat_rain"),
    ]

    operations = [
        migrations.AddField(
            model_name="jetsettings",
            name="bot_chat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jetsettings",
            name="bot_chat_per_minute",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="jetchatmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chat", "Player message"),
                    ("win", "Big win"),
                    ("rain", "Rain"),
                    ("system", "Notice"),
                    ("bot", "Simulated player"),
                ],
                default="chat",
                max_length=8,
            ),
        ),
    ]
