# Generated by Django 5.1.15 on 2026-09-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(unique=True)),
                ("code", models.CharField(max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "revshare_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cpa_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cpa_min_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("website", models.CharField(blank=True, max_length=200)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "affiliates_affiliate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(unique=True)),
                ("campaign", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="affiliates.affiliate",
                    ),
                ),
            ],
            options={
                "db_table": "affiliates_referral",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign", models.CharField(blank=True, max_length=50)),
                ("landing", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="affiliates.affiliate",
                    ),
                ),
            ],
            options={
                "db_table": "affiliates_click",
                "indexes": [
                    models.Index(
                        fields=["affiliate", "created_at"],
                        name="affiliates__affilia_52c204_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("revshare", "Revenue share"), ("cpa", "CPA")],
                        max_length=10,
                    ),
                ),
                ("period", models.DateField(blank=True, null=True)),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("active_players", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved (paying)"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="affiliates.affiliate",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="affiliates.referral",
                    ),
                ),
            ],
            options={
                "db_table": "affiliates_commission",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="affiliates__status_ec6c34_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "revshare")),
                        fields=("affiliate", "period"),
                        name="one_revshare_per_affiliate_month",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "cpa")),
                        fields=("referral",),
                        name="one_cpa_per_referral",
                    ),
                ],
            },
        ),
    ]
