# Generated by Django 5.1.15 on 2026-10-09 22:09

import django.db.models.deletion
from django.db import migrations, models


def existing_affiliates_get_deposit_commission(apps, schema_editor):
    # Affiliates who joined before deposit commission existed start on the new
    # default (30% of a referral's first deposit, up to 100). Any commission
    # this creates still waits for operator approval unless auto-pay is on.
    Affiliate = apps.get_model('affiliates', 'Affiliate')
    Affiliate.objects.filter(cpa_percent=0).update(cpa_percent=30, cpa_cap=100)


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_bonus_percent",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "welcome_bonus_cap",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "welcome_bonus_wagering",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "welcome_bonus_min_deposit",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "default_revshare_percent",
                    models.DecimalField(decimal_places=2, default=25, max_digits=5),
                ),
                (
                    "default_cpa_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "default_cpa_min_deposit",
                    models.DecimalField(decimal_places=2, default=20, max_digits=10),
                ),
                (
                    "default_cpa_percent",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "default_cpa_cap",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "cpa_min_turnover_multiple",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("negative_carryover", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "affiliates_programme",
            },
        ),
        migrations.AddField(
            model_name="affiliate",
            name="cpa_cap",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="affiliate",
            name="cpa_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="RevshareMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("ngr", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "carried_in",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "carry_out",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revshare_months",
                        to="affiliates.affiliate",
                    ),
                ),
                (
                    "commission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="month",
                        to="affiliates.commission",
                    ),
                ),
            ],
            options={
                "db_table": "affiliates_revshare_month",
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("affiliate", "period"),
                        name="one_revshare_month_per_affiliate",
                    )
                ],
            },
        ),
        migrations.RunPython(existing_affiliates_get_deposit_commission, migrations.RunPython.noop),
    ]
