# Generated by Django 5.1.15 on 2026-10-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0002_deposit_commission_welcome_bonus_carryover"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliateprogramme",
            name="external_payouts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="affiliateprogramme",
            name="min_payout",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("wallet", "Betting wallet"),
                            ("ecocash", "EcoCash"),
                            ("onemoney", "OneMoney"),
                            ("innbucks", "InnBucks"),
                            ("bank", "Bank transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=60)),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="affiliates.affiliate",
                    ),
                ),
            ],
            options={
                "db_table": "affiliates_payout",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="affiliates__status_8a09f6_idx",
                    )
                ],
            },
        ),
    ]
