# Generated by Django 5.1.15 on 2026-06-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit Bonus"),
                            ("freebet", "Free Bet"),
                            ("cashback", "Cashback"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "wagering_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "promotions_promotion",
                "ordering": ["-active", "name"],
            },
        ),
        migrations.CreateModel(
            name="PromotionClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "wagering_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wagering_progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("forfeited", "Forfeited"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("bonus_credited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotions_claim",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player_id", "promotion"),
                        name="uniq_player_promotion_claim",
                    )
                ],
            },
        ),
    ]
