# Generated by Django 5.1.15 on 2026-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="promotion",
            name="terms_html",
            field=models.TextField(blank=True),
        ),
    ]
