# Generated by Django 5.1.15 on 2026-06-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_promotion_code_promotion_terms_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[("wagered", "Total wagered")],
                        default="wagered",
                        max_length=20,
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "promotions_tournament",
                "ordering": ["-active", "-ends_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("player_name", models.CharField(blank=True, max_length=150)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="promotions.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "promotions_tournament_entry",
                "ordering": ["-score", "updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "player_id"),
                        name="uniq_tournament_player",
                    )
                ],
            },
        ),
    ]
