# Generated by Django 5.1.15 on 2026-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_tournament_tournamententry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("image_url", models.CharField(max_length=500)),
                ("link_url", models.CharField(blank=True, max_length=500)),
                ("cta_label", models.CharField(blank=True, max_length=60)),
                (
                    "placement",
                    models.CharField(
                        choices=[("home_hero", "Homepage hero")],
                        default="home_hero",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "promotions_banner",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
