# Generated by Django 5.1.15 on 2026-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0004_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="placement",
            field=models.CharField(
                choices=[("home_hero", "Homepage hero"), ("sportsbook", "Sportsbook")],
                default="home_hero",
                max_length=20,
            ),
        ),
    ]
