# Generated by Django 5.1.15 on 2026-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_remove_demo_banners"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.BinaryField()),
                ("content_type", models.CharField(max_length=40)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "promotions_bannerimage",
            },
        ),
    ]
