# Generated by Django 5.1.15 on 2026-07-01 17:32

import apps.branding.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("light", models.JSONField(default=apps.branding.tokens.default_light)),
                ("dark", models.JSONField(default=apps.branding.tokens.default_dark)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_username", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "branding_site_theme",
            },
        ),
    ]
