# Generated by Django 5.1.15 on 2026-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="SLÝKBETS", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Bet smart. Brag often.", max_length=120
                    ),
                ),
                ("logo_url", models.CharField(blank=True, max_length=500)),
                (
                    "license_text",
                    models.TextField(
                        blank=True,
                        default="Licensed and regulated by the Lotteries and Gaming Board of Zimbabwe. Licence No. LGB/SLYKBETS/2026 (demo).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_username", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "branding_site_identity",
            },
        ),
    ]
