# Generated by Django 5.1.15 on 2026-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="player",
            name="loyalty_tier",
            field=models.CharField(
                choices=[("bronze", "Bronze"), ("silver", "Silver"), ("gold", "Gold")],
                default="bronze",
                max_length=20,
            ),
        ),
    ]
