# Generated by Django 5.1.15 on 2026-06-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_player_avatar_url_player_loyalty_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="suspended_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("national_id", "National ID"),
                            ("driving_license", "Driving license"),
                            ("proof_of_address", "Proof of address"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="kyc/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_submissions",
                        to="accounts.player",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_kyc_submission",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
