# Generated by Django 5.1.15 on 2026-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_player_is_suspended_player_suspended_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("bet_placed", "Bet placed"),
                    ("bet_settled", "Bet settled"),
                    ("casino_spin", "Casino spin"),
                    ("promo_claim", "Promotion claimed"),
                    ("self_exclude", "Self-exclusion"),
                    ("limit_set", "Deposit limit set"),
                    ("email_verified", "Email verified"),
                    ("password_reset", "Password reset"),
                    ("data_export", "Data export"),
                    ("account_deleted", "Account deleted"),
                    ("kyc_submitted", "KYC document submitted"),
                    ("kyc_approved", "KYC approved"),
                    ("kyc_rejected", "KYC rejected"),
                    ("player_suspended", "Player suspended"),
                    ("player_unsuspended", "Player unsuspended"),
                    ("balance_adjusted", "Balance adjusted"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
