# Generated by Django 5.1.15 on 2026-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_auditlog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="player",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
