# Generated by Django 5.1.15 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_kyc_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("bet_placed", "Bet placed"),
                    ("bet_settled", "Bet settled"),
                    ("event_settled", "Event settled (result)"),
                    ("event_settled_score", "Event settled (score)"),
                    ("market_settled", "Market settled"),
                    ("casino_spin", "Casino spin"),
                    ("promo_claim", "Promotion claimed"),
                    ("self_exclude", "Self-exclusion"),
                    ("limit_set", "Deposit limit set"),
                    ("email_verified", "Email verified"),
                    ("password_reset", "Password reset"),
                    ("data_export", "Data export"),
                    ("account_deleted", "Account deleted"),
                    ("kyc_submitted", "KYC document submitted"),
                    ("kyc_approved", "KYC approved"),
                    ("kyc_rejected", "KYC rejected"),
                    ("player_suspended", "Player suspended"),
                    ("player_unsuspended", "Player unsuspended"),
                    ("balance_adjusted", "Balance adjusted"),
                    ("theme_updated", "Site theme updated"),
                    ("identity_updated", "Site identity updated"),
                    ("affiliate_applied", "Affiliate applied"),
                    ("affiliate_status", "Affiliate status changed"),
                    ("affiliate_terms", "Affiliate terms changed"),
                    ("affiliate_commission_paid", "Affiliate commission paid"),
                    ("feed_settings_changed", "Odds feed settings changed"),
                    ("event_edited", "Match edited by staff"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
