# Generated by Django 5.1.15 on 2026-06-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True, unique=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallet_wallet",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("bet_stake", "Bet stake (debit)"),
                            ("bet_payout", "Bet payout (credit)"),
                            ("casino_debit", "Casino debit"),
                            ("casino_credit", "Casino credit"),
                            ("bonus", "Bonus credit"),
                            ("adjustment", "Manual adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_ledger_entry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="wallet_ledg_wallet__fa2518_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="wallet_ledg_referen_26220e_idx"
                    ),
                ],
            },
        ),
    ]
