# Generated by Django 5.1.15 on 2026-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="wallet_balance_non_negative",
            ),
        ),
    ]
