# Generated by Django 5.1.15 on 2026-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallet_balance_non_negative_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("bet_stake", "Bet stake (debit)"),
                    ("bet_payout", "Bet payout (credit)"),
                    ("casino_debit", "Casino debit"),
                    ("casino_credit", "Casino credit"),
                    ("bonus", "Bonus credit"),
                    ("adjustment", "Manual adjustment"),
                    ("affiliate", "Affiliate commission"),
                ],
                max_length=20,
            ),
        ),
    ]
