# Generated by Django 5.1.15 on 2026-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_ledgerentry_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("provider", models.CharField(default="paynow", max_length=20)),
                ("method", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid (credited)"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=64)),
                ("provider_status", models.CharField(blank=True, max_length=40)),
                ("poll_url", models.URLField(blank=True, max_length=500)),
                ("redirect_url", models.URLField(blank=True, max_length=500)),
                ("instructions", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet_paymenttransaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
