# Generated by Django 5.1.15 on 2026-10-08 09:53

from django.db import migrations, models


# The methods the deposit screen and footer offered before they were editable.
SEED = [
    dict(code='ecocash', name='EcoCash', description='Mobile money', speed='Instant', logo_text='EC',
         color='#e2231a', field='phone', sort_order=10),
    dict(code='onemoney', name='OneMoney', description='Mobile money', speed='Instant', logo_text='OM',
         color='#0aa14b', field='phone', sort_order=20),
    dict(code='innbucks', name='InnBucks', description='Wallet', speed='Instant', logo_text='IB',
         color='#6d28d9', field='phone', sort_order=30),
    dict(code='card', name='Visa / Mastercard', description='Debit or credit card', speed='1–2 min',
         logo_text='••', color='#1a1f71', field='card', sort_order=40),
    dict(code='usdt', name='USDT (TRC-20)', description='Crypto', speed='~1 min', logo_text='₮',
         color='#26a17b', field='crypto', sort_order=50),
]


def seed_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('wallet', 'PaymentMethod')
    for row in SEED:
        PaymentMethod.objects.get_or_create(code=row['code'], defaults=row)


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_payment_transactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, max_length=120)),
                (
                    "speed",
                    models.CharField(blank=True, default="Instant", max_length=30),
                ),
                ("logo_text", models.CharField(blank=True, max_length=3)),
                (
                    "color",
                    models.CharField(
                        default="#4f46e5",
                        help_text="Logo tile colour, #rrggbb.",
                        max_length=7,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("phone", "Mobile number"),
                            ("card", "Card"),
                            ("crypto", "Crypto address"),
                            ("none", "Nothing to enter"),
                        ],
                        default="phone",
                        max_length=8,
                    ),
                ),
                ("deposit_enabled", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=True)),
                (
                    "min_deposit",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "max_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallet_paymentmethod",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RunPython(seed_methods, migrations.RunPython.noop),
    ]
