# Generated by Django 5.1.15 on 2026-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_payment_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Use the server setting"),
                            ("stub", "Test processor (no money moves)"),
                            ("paynow", "Paynow"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("paynow_integration_id", models.CharField(blank=True, max_length=20)),
                (
                    "paynow_integration_key",
                    models.CharField(blank=True, max_length=100),
                ),
                ("paynow_auth_email", models.EmailField(blank=True, max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_username", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "wallet_paymentgateway",
            },
        ),
    ]
