# Generated by Django 5.1.15 on 2026-10-11 06:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_payment_gateway"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ecocash", "EcoCash"),
                            ("onemoney", "OneMoney"),
                            ("innbucks", "InnBucks"),
                            ("bank", "Bank transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(max_length=60)),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Waiting to be paid"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("decided_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet_withdrawal_request",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1000.00"), max_digits=12
                    ),
                ),
                (
                    "daily_max",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000.00"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallet_withdrawal_settings",
            },
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("withdrawal_hold", "Withdrawal held"),
                    ("bet_stake", "Bet stake (debit)"),
                    ("bet_payout", "Bet payout (credit)"),
                    ("casino_debit", "Casino debit"),
                    ("casino_credit", "Casino credit"),
                    ("bonus", "Bonus credit"),
                    ("adjustment", "Manual adjustment"),
                    ("affiliate", "Affiliate commission"),
                ],
                max_length=20,
            ),
        ),
    ]
