# Generated by Django 5.1.15 on 2026-06-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(default="stub", max_length=80)),
                (
                    "rtp",
                    models.DecimalField(decimal_places=2, default=96.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "casino_game",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "win",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (debit unconfirmed)"),
                            ("settled", "Settled"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("debit_confirmed", models.BooleanField(default=False)),
                ("provider_round_ref", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="casino.game",
                    ),
                ),
            ],
            options={
                "db_table": "casino_round",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "debit_confirmed", "created_at"],
                        name="casino_roun_status_ccfc02_idx",
                    )
                ],
            },
        ),
    ]
