# Generated by Django 5.1.15 on 2026-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casino", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
