# Generated by Django 5.1.15 on 2026-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casino", "0002_game_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.CharField(
                choices=[
                    ("slots", "Slots"),
                    ("crash", "Crash"),
                    ("live", "Live Casino"),
                    ("table", "Table Games"),
                    ("virtual", "Virtual Sports"),
                    ("instant", "Instant Win"),
                ],
                db_index=True,
                default="slots",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CrashRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.BigIntegerField(db_index=True)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                ("crash_point", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cashout_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "win",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("cashed", "Cashed out"),
                            ("busted", "Busted"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("debit_confirmed", models.BooleanField(default=False)),
                ("server_seed", models.CharField(max_length=80)),
                ("server_seed_hash", models.CharField(max_length=80)),
                ("nonce", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "casino_crash_round",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="casino_cras_status_919bf2_idx",
                    )
                ],
            },
        ),
    ]
